Certain conditions caused a NoMethodError: undefined method `include?' for nil:NilClass when dispatching through 'method transitions' in RepresentorAgent.
This replicates that condition and supplies the fix whereby an empty has is returned instead of nil.